### PR TITLE
Escape zfs property values

### PR DESCRIPTION
**Pull request by miks**

### CODE REVIEW

**Comment by miks** [comment]
This is extracted from #14.
Otherwise there is no way how to send/receive volumes with property values which have characters like  slashes, & and others which will break arguments.

**Comment by miks** [comment]
Thanks. Is there any release plans?

**Comment by allanjude** [comment]
yes. I am working on solving an issue where it deletes all the snapshots randomly, causing full re-replication, which is really killing me with 500gb datasets over the internet

**Comment by miks** [comment]
Ok, no rush.

**Pull request merged**
